SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE `Maitred`;
DROP TABLE `Manager`;
DROP TABLE `AssignedTables`;
DROP TABLE `LineCook`;
DROP TABLE `MenuItemSet`;
DROP TABLE `Recipes`;
DROP TABLE `MentorShip`;
DROP TABLE `HeadChef`;
DROP TABLE `SousChef`;
DROP TABLE `Chef`;
DROP TABLE `Spices`;
DROP TABLE `Categories`;
DROP TABLE `Corporation`;
DROP TABLE `Customers`;
DROP TABLE `Employee`;
DROP TABLE `Menu`;
DROP TABLE `MenuItem`;
DROP TABLE `MenuMI`;
DROP TABLE `Order`;
DROP TABLE `OrderDetails`;
DROP TABLE `ShiftCrew`;
DROP TABLE `WaitStaff`;
SET FOREIGN_KEY_CHECKS = 1;

